<a href="https://colab.research.google.com/github/MaheshReddy0806/B14_PDS_10H1/blob/main/LAB%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

marks = np.array([

    [78, 85, 90],

    [92, 88, 79],

    [65, 70, 60],

    [89, 94, 91],

    [55, 60, 58]

])

print("Student Marks (Rows: Students, Columns: Subjects):")

print(marks)

average_per_student = np.mean(marks, axis=1)

min_per_student = np.min(marks, axis=1)

max_per_student = np.max(marks, axis=1)

average_overall = np.mean(marks)

min_overall = np.min(marks)

max_overall = np.max(marks)

print("\nAverage marks per student:", average_per_student)

print("Minimum marks per student:", min_per_student)

print("Maximum marks per student:", max_per_student)

print("\nOverall average marks:", average_overall)

print("Overall minimum marks:", min_overall)

print("Overall maximum marks:", max_overall)

selected_students = marks[[0, 2]]

print("\nMarks of first and third student:")

print(selected_students)

above_80 = marks > 80

print("\nBoolean mask for marks above 80:")

print(above_80)

students_above_80 = np.any(above_80, axis=1)

print("\nStudents who scored above 80 in at least one subject:")

print(marks[students_above_80])

subject_wise = marks.T

print("\nSubject-wise marks (Rows: Subjects, Columns: Students):")

print(subject_wise)

subject_avg = np.mean(subject_wise, axis=1)

print("\nAverage marks per subject (Math, Science, English):")

print(subject_avg)




Student Marks (Rows: Students, Columns: Subjects):
[[78 85 90]
 [92 88 79]
 [65 70 60]
 [89 94 91]
 [55 60 58]]

Average marks per student: [84.33333333 86.33333333 65.         91.33333333 57.66666667]
Minimum marks per student: [78 79 60 89 55]
Maximum marks per student: [90 92 70 94 60]

Overall average marks: 76.93333333333334
Overall minimum marks: 55
Overall maximum marks: 94

Marks of first and third student:
[[78 85 90]
 [65 70 60]]

Boolean mask for marks above 80:
[[False  True  True]
 [ True  True False]
 [False False False]
 [ True  True  True]
 [False False False]]

Students who scored above 80 in at least one subject:
[[78 85 90]
 [92 88 79]
 [89 94 91]]

Subject-wise marks (Rows: Subjects, Columns: Students):
[[78 92 65 89 55]
 [85 88 70 94 60]
 [90 79 60 91 58]]

Average marks per subject (Math, Science, English):
[75.8 79.4 75.6]
